# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3517b82ffa8593d15f80273e46d39c07e7ff827136d1073420189648a80eecedb738705681df4de371153f16aa9927cebd9800af90536fa35f7621ab452b73b

test:
  secret_key_base: 4fe511b9e70b944c17a01fc77b988f425f56eedca9c188ebec5aaf620d515e50e61ac8d1b9a9057d02b1f863310ee6d2611825f26e9fe23c03e7752456bdf7ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
